# Generated by Django 5.2.8 on 2025-11-26 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0002_alter_service_image_alter_siteinfo_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dataset_type', models.CharField(choices=[('anomaly_detection', 'Anomaly Detection'), ('sales_forecast', 'Sales Forecasting'), ('inventory_optimization', 'Inventory Optimization'), ('quality_control', 'Quality Control')], max_length=50)),
                ('description', models.TextField()),
                ('data_file', models.FileField(upload_to='datasets/')),
                ('columns', models.JSONField(default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('product_alert', 'Product Alert'), ('order_update', 'Order Update'), ('system_alert', 'System Alert'), ('urgent_alert', 'Urgent Alert')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('stock_low', 'Low Stock'), ('expiry_near', 'Near Expiry'), ('quality_issue', 'Quality Issue'), ('temperature_anomaly', 'Temperature Anomaly'), ('humidity_issue', 'Humidity Issue'), ('ai_anomaly', 'AI Detected Anomaly')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('detected_by', models.CharField(max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bika.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('anomaly_detection', 'Anomaly Detection'), ('sales_forecast', 'Sales Forecasting'), ('stock_prediction', 'Stock Prediction')], max_length=50)),
                ('model_file', models.FileField(upload_to='trained_models/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feature_columns', models.JSONField(default=list)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bika.productdataset')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('weight', 'Weight'), ('vibration', 'Vibration'), ('pressure', 'Pressure')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bika.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bika.storagelocation')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'sensor_type', 'recorded_at'], name='bika_realti_product_bd8763_idx')],
            },
        ),
    ]
